README.md
src/Listener/ViewListener.php
src/Template/Element/form.ctp
src/Template/Element/index/bulk_actions/form_end.ctp
src/Template/Element/view/related/has_many.ctp
src/Template/Layout/default.ctp
src/Template/Scaffolds/index.ctp
src/Template/Scaffolds/view.ctp
src/View/CrudView.php
src/View/Helper/CrudViewHelper.php

Fix has-many view template

---

src/View/Helper/CrudViewHelper.php

This makes it more user friendly as the area for clicking the details
of a row is bigger.

Converts the table display field into a link for the view action.

---

src/Template/Scaffolds/view.ctp

This makes it look tidier as there are styles that can be applied to
the table automatically.
Also, this brings it in line to how bake outputs the view in 3.1

Using a table instead of a definition list in the view action.

---

src/Listener/ViewListener.php
src/Template/Cell/TablesList/display.ctp
src/Template/Element/sidebar.ctp
src/View/Cell/TablesListCell.php

This avoid unnecessary fetching of tables list from db
if someone want to use an alternate solution.

Create a cell for sidebar's tables list.

---

src/View/Helper/CrudViewHelper.php

Refs friendsofcake/crud#294
~~Crud should probably be tagged before merging this so as not to cause any BC issues.~~
Done

Rename redirect_url to _redirect_url.

---

config/asset_compress.ini
config/defaults.php
src/Template/Element/search.ctp
webroot/css/local.css
webroot/js/local.js

Adding selectize.js to implement search filters autocompletion

---

src/Listener/ViewListener.php

Earlier it showed "Add Post #" now it's "Add Post".

Fix trailing "#" shown for add action's title.

---

src/Template/Element/actions.ctp

This allows the closure to have access to view helpers.

Pass view instance to callback.

---

src/Listener/ViewListener.php

Very often it's necessary to have extra actions for an entity (besides default CRUD actions).
Extra actions are just standard cake's controller actions.
Usage example:
```
// configuration in a controller
$action->config('scaffold.extra_actions', [
'unpublish', // short action definition
'activate' => ['scope' => 'entity', 'method' => 'GET'] // customized action settings
]);
// implemented actions in the controller
public function unpublish($id) 
{
// code...
}
public function activate($id) 
{
// code...
}
```

Added possibility to define custom extra actions

---

config/asset_compress.ini
src/Listener/ViewListener.php

Add missing Javascript file to asset compress config

---

src/Listener/ViewListener.php

`Add` view was affected by changes provided in PR #71.

Fixed associations bug on add view (intoduced by PR #71)

---

src/Listener/ViewListener.php

Usage:
```
// controller code
$action->config('scaffold.actions', [
'edit' => ['target' => '_blank']
]);
```

Added possibility to pass options to action links

---

src/Listener/ViewListener.php

```php
// before
$action->config('scaffold.actions_blacklist', ['view', 'index', 'add', 'edit', 'delete']);
// after
$action->config('scaffold.actions', false);
```

Allow disabling all action links

---

src/Listener/ViewListener.php
src/Template/Element/actions.ctp

Action callbacks were not supported after "Actions groups" feature was introduced.
Fixed now.

Fixed action callbacks

---

docs/_themes/cakephp/layout.html
docs/customizing-templates.rst

Some small fixes in the `crud-view` docs.

Docs fixes

---

src/View/Widget/DateTimeWidget.php

wrapping the calendar icon in a label instead of span

---

webroot/js/local.js

by allowing multi-select lists and control over some more options:
- `maxOptions`: using `data-max-options`
- `maxItems`: using `data-max-items`
- `hideSelected`: using `data-hide-selected`
- `closeAfterSelect`: using `data-close-after-select`

Improve selectizer options

---

src/Template/Element/action-header.ctp
src/Template/Element/actions.ctp
webroot/css/local.css

Move header buttons inline with header

---

src/Template/Element/action-header.ctp
webroot/css/local.css

Move back table action buttons below header.

---

src/View/Helper/CrudViewHelper.php

This allows easier overriding and better control over generated output.

Add formatDisplayField() and columnType() methods to CrudViewHelper.

---

src/Listener/ViewSearchListener.php

This will allow disabling the default use of autocomplete and selectize without breaking bownty apps :)

Allow configuring default use of selectize and autocomplete.

---

src/View/Widget/DateTimeWidget.php

DateTimeWidget is missing support for disabled state on inputs.

Add support for disabled state to datetime

---

src/View/Widget/DateTimeWidget.php

Fixes #139 
Key is not set by default.

FIX: Disabled key is not set by default

---

config/defaults.php

https://github.com/selectize/selectize.js/issues/739

Update selectize to 0.12.2

---

src/Listener/ViewListener.php
src/Listener/ViewSearchListener.php
src/Template/Element/view/related/has_many.ctp
src/Template/Element/view/related/has_one.ctp
src/View/CrudView.php
src/View/Helper/CrudViewHelper.php
src/View/Widget/DateTimeWidget.php

- Add options param for createRelationLink
- Using buttons instead of simple links with related elements

Related elements

---

src/View/Widget/DateTimeWidget.php

- Get timezone only if required.
- Allow specifying custom locale.

Datetimewidget

---

docs/_themes/cakephp/relbar1.html
docs/_themes/cakephp/static/css/app.css
docs/contents.rst
docs/general-configuration/utility-navigation.rst
src/Listener/Traits/SiteTitleTrait.php
src/Listener/Traits/UtilityNavigationTrait.php
src/Listener/ViewListener.php
src/Menu/MenuDivider.php
src/Menu/MenuDropdown.php
src/Menu/MenuItem.php
src/Template/Element/menu/divider.ctp
src/Template/Element/menu/dropdown.ctp
src/Template/Element/menu/item.ctp
src/Template/Element/topbar.ctp
src/Template/Layout/default.ctp

Looks like the following:
Also includes docs. Closes #111

feat: add utility navigation for deciding contents of top-right

---

docs/_themes/cakephp/static/css/app.css
docs/contents.rst
docs/general-configuration/sidebar-navigation.rst
docs/general-configuration/utility-navigation.rst
src/Listener/Traits/SidebarNavigationTrait.php
src/Listener/Traits/UtilityNavigationTrait.php
src/Listener/ViewListener.php
src/Template/Element/sidebar.ctp

Also document scaffold.tables and scaffold.tables_blacklist
Looks like this:

Sidebar navigation

---

docs/general-configuration/utility-navigation.rst
src/Listener/Traits/UtilityNavigationTrait.php

- feat: set default utility navigation to match documentation
- docs: add note as to how to disable the utility_navigation

Utility navigation updates

---

src/Template/Layout/default.ctp

Fix issue where the page title is unexpectedly set to the brand

---

composer.json

Update bootstrap-ui requirement

---

src/Listener/ViewListener.php

fix: drop messages from options sent to the view layer

---

docs/index-pages/customizing-the-index-page.rst
src/Listener/ViewListener.php
src/Template/Element/action-groups.ctp
src/Template/Element/actions.ctp

- Add documentation!
- Cleanup action groups
- Add the ability to specify where the primaryKey will appear in the generated url

Clean up index action button implementation

---

docs/index-pages/components/blog.rst
docs/index-pages/components/gallery.rst
src/Listener/Traits/IndexTypeTrait.php
src/Template/Element/index/blog.ctp
src/Template/Element/index/gallery.ctp
src/Template/Scaffold/index.ctp
webroot/css/local.css

Gallery index type

---

src/View/Widget/DateTimeWidget.php

Fix issue of input generated by datetimewidget with SecurityComponent.

---

docs/index-pages/customizing-the-index-page.rst
src/Listener/Traits/IndexTypeTrait.php
src/Template/Element/index/finder_scopes.ctp
src/Template/Scaffold/index.ctp

Also includes example for actually applying the scopes.
Closes #175

feat: implement finder scopes

---

docs/_partials/pages/index/download-format-links.rst
docs/index-pages/customizing-the-index-page.rst
src/Listener/Traits/IndexTypeTrait.php
src/Template/Element/index/download_formats.ctp
src/Template/Element/index/pagination.ctp
webroot/css/local.css

Also includes a sample for integrating with CsvView.
Closes #174

feat: Add the ability to specify "format as" buttons

---

docs/_partials/pages/index/bulk-actions.rst
docs/basic-usage.rst
docs/index-pages/customizing-the-index-page.rst

docs: Add documentation to index page surrounding bulk actions

---

.travis.yml
composer.json
docs/_partials/pages/index/download-format-links.rst
docs/_partials/pages/index/finder-scopes.rst
docs/basic-usage.rst
src/Listener/Traits/FormTypeTrait.php
src/Listener/Traits/IndexTypeTrait.php
src/Listener/Traits/SidebarNavigationTrait.php
src/Listener/Traits/SiteTitleTrait.php
src/Listener/Traits/UtilityNavigationTrait.php
src/Listener/ViewListener.php
src/Listener/ViewSearchListener.php
src/View/Helper/CrudViewHelper.php

- upgrade to minimum cakephp 3.4
- use non-deprecated methods for data retrieval
- add a few scrutinizer fixes
- support all the official versions of php that cakephp supports

Upgrade cakephp

---

config/defaults.php
docs/basic-usage.rst
docs/general-configuration/site-title-options.rst
docs/index-pages/components/blog.rst
src/Listener/Traits/FormTypeTrait.php
src/Listener/Traits/IndexTypeTrait.php
src/Listener/Traits/SidebarNavigationTrait.php
src/Listener/Traits/SiteTitleTrait.php
src/Listener/ViewListener.php
src/Template/Element/form.ctp

Remove deprecated code

---

src/Listener/SearchListener.php

Use the ViewSearchListener instead.

fix: Remove deprecated SearchListener class

---

docs/_partials/fields/field-groups.rst
docs/_partials/fields/tab-groups.rst
docs/form-pages/customizing-the-form-page.rst
src/Listener/ViewListener.php
src/Template/Element/form.ctp
src/Template/Element/form/tabs.ctp

Feat: Allow showing form fields in tabs.

---

config/defaults.php
docs/general-configuration/sidebar-navigation.rst
src/Template/Element/sidebar.ctp

Add global tables blacklist.

---

docs/customizing-templates.rst

Add example of custom controller action

---

src/Listener/Traits/FormTypeTrait.php
src/Template/Element/form/buttons.ctp

- Set value for default "Save" button.
Without a value you can't set a redirect reader (for RedirectListener) for it.
- Move default buttons config to separate method for easy extension.

Form buttons

---

.editorconfig
webroot/js/local.js

This change for e.g. allows me to reuse the autocomplete handler setup code for inputs dynamically added to the form.

Organize code using javascript object literal.

---

src/View/Helper/CrudViewHelper.php

This allows users to use helpers within callables for formatting.

feat: pass in the View object to field formatters

---

docs/_partials/pages/index/filters.rst

The parameters were incorrect for usage with Crud.

docs: clarify how to use the ViewSearchListener

---

.travis.yml
composer.json
docs/.editorconfig
docs/_partials/fields/formatter-callable.rst
phpunit.xml.dist
src/View/CrudView.php
src/View/Helper/CrudViewHelper.php
tests/TestCase/View/CrudViewTest.php
tests/TestCase/View/Helper/CrudViewHelperTest.php
tests/bootstrap.php

Add ability to set field formatters based on column type.

---

src/Template/Element/actions.ctp

feat: allow changing action button class

---

docs/_partials/pages/index/buttons.rst
src/Listener/ViewListener.php

feat: Blacklist Crud.LookupAction by default

---

src/Listener/ViewListener.php

Check commit messages for details.

Action links config

---

composer.json
src/Listener/ViewListener.php
src/Listener/ViewSearchListener.php
src/Template/Element/actions.ctp
src/Template/Element/index/bulk_actions/form_end.ctp
src/Template/Element/search.ctp
src/Template/Layout/default.ctp
src/View/Cell/TablesListCell.php
src/View/Helper/CrudViewHelper.php
src/View/Widget/DateTimeWidget.php

cakephp 3.6 deprecation fixes

---

config/defaults.php
webroot/js/local.js

https://github.com/select2/select2
Selectize is buggy and doesn't seem to be maintained currently.
I have retained it's use for autocomplete() as I haven't used that feature
and thus not sure of the changes required to use select2 instead.

Use select2 instead of selectize.

---

templates/element/action-groups.php
templates/element/actions.php
templates/element/form/buttons.php
webroot/css/local.css

This causes design issue when using additional themes / widgets.
Just use whitespace for spacing between action buttons.
See https://getbootstrap.com/docs/4.3/components/buttons/

Don't add margins to all buttons by default.

---

config/defaults.php
phpstan.neon
src/Listener/ViewSearchListener.php
webroot/js/local.js

Implement autocomplete using select2.

---

src/Listener/ViewSearchListener.php

https://book.cakephp.org/4/en/development/routing.html#generating-urls

Use '?' as array key for lookup query

---

templates/cell/TablesList/display.php
templates/element/form/buttons.php
templates/element/index/table.php
templates/element/menu/divider.php
templates/element/menu/item.php
templates/element/sidebar.php
templates/element/topbar.php
templates/element/view/related/has_many.php
templates/element/view/related/has_one.php
templates/layout/default.php

Update HTML & code for bootstrap 4

---

templates/element/view/related/has_many.php

Fix delete link for related records.

---

webroot/js/local.js

Fixed variable name in local.js:50

---

src/Listener/ViewSearchListener.php
tests/Fixture/BlogsFixture.php
tests/TestCase/Listener/ViewSearchListenerTest.php

Don't override user provided "data-url".

---

src/Listener/ViewSearchListener.php
tests/Fixture/BlogsFixture.php
tests/TestCase/Listener/ViewSearchListenerTest.php

Add empty option by default for search form selects.
