FriendsOfCake/crud-view

Listener/ViewListener.php, README.md, View/CrudView.php, View/Widget/BasicWidget.php, View/Widget/DateTimeWidget.php, View/Widget/LabelWidget.php, View/Widget/SelectBoxWidget.php, View/Widget/TextareaWidget.php
Some recent core changes have broken things:
- `MissingViewException` is now `MissingTemplateException`
- Classes in `View/Widget/` are now named with `Widget` suffix
This PR gets things (mostly) working again.
=> Make CrudView work again

src/Listener/SearchListener.php, src/Template/Element/search.ctp
* The form was using the FormHelper wrongly
* Made The listener use the unique search field name instead of using th field directly,
this is because we cannot assume that the field name actually maps to the search param.
=> Fixing the SearchListener and search form:

src/Listener/ViewListener.php
I see no reason for limiting the users to just the fields in the schema
=> Allowing users to also pass virtual fields to the scaffold views

src/Listener/ViewListener.php
Also, messing with contain() when it is already set in the pagination query
is annoying and difficult to overcome. This respects the user query if it
is already defined.
=> Loading hasMany and belongsToMany by default in index views is wasteful.

src/View/Widget/DateTimeWidget.php, webroot/js/local.js
This moves the JS to `local.js` and allows for more configuration (format / locale) to be passed to the widget (and picker's JS) using `data-*`.
/cc @lorenzo @ADmad
=> Make datetime picker configurable

src/View/Helper/CrudViewHelper.php
This was needed because the link to view function was
double escaping the contents.
=> Adding an options parameter to createViewLink

src/View/Helper/CrudViewHelper.php
Cake's Time::nice() expects the second parameter to be a string or null (not an array).
http://api.cakephp.org/3.0/class-Cake.I18n.Time.html#_nice
=> Fixed bug in CrudViewHelper::formatTime function

src/Listener/ViewListener.php, src/Template/Element/form.ctp
More advanced "extra buttons" management for edit view.
Besides "disable all" now it's possible to specify which exactly buttons have to be disabled.
Usage:
```
if ($this->request->action === 'edit') {
$action->config('scaffold.extra_buttons_blacklist', [
'save_and_continue', 'save_and_create', 'back'
]);
}
```
P.S. Does it make sense to have `disableExtraButtons` option if more advanced option is available?
=> Added extraButtonsBlacklist feature.

composer.json
Travis already has phpunit. We can add back specific version if the one
provided by travis causes issues in future. Locally one can just use
phpunit.phar or globally installed phpunit.
Closes #13
Currently we don't have tests anyway :)
=> Remove phpunit from "require-dev".

src/View/Helper/CrudViewHelper.php
Sometimes it makes sense to display "No" as success (green) and "Yes" as danger (red). 
For example fields like "is_deleted", "is_deactivated", "is_banned" etc. It would be nice to have green "No" for such situations.
Usage:
```php
// in a controller
$fields['is_deactivated'] = ['inverted' => true];
$action->config('scaffold.fields', $fields);
```
=> Inverted booleans format (green No and red Yes) [rePR]

src/Template/Element/action-header.ctp, src/Template/Scaffold/view.ctp
The issue:
Only "Index" action is available on "View" page.
Nothing at all is available on "Edit" page.
This PR fixes the issue.
All available actions are shown on the edit/view pages.
=> Added more actions on view/edit pages

config/defaults.php, src/Listener/ViewListener.php, src/Template/Element/form.ctp, webroot/js/local.js
Show "Are you sure?" warning if a page is closed/reloaded while form contains unsaved changes.
The option `enable_dirty_check` is **disabled** by default.
To enable it:
```
// in a controller
if ($this->request->action === 'edit') {
$action->config('scaffold.enable_dirty_check', true);
}
```
=> Feature proposal: Detect unsaved changes and show warning on page close

src/Listener/ViewListener.php, src/Template/Element/action-button.ctp, src/Template/Element/action-groups.ctp, src/Template/Element/action-header.ctp, src/Template/Element/actions.ctp, webroot/css/local.css, webroot/js/local.js
Added possibility to group actions. Few actions can be grouped into one dropdown list.
Config:
```    
// in a controller
$action->config('scaffold.action_groups', [
'Extras' => ['edit', 'publish', 'deactivate']
]);
```
Result:
Important notes
- Actions out of groups will be rendered as separate buttons (like "View" on the image above)
- Scope (entity OR table) is still defined by an action, not a group. It means if no actions are available in the current scope a group will be just ignored and not rendered.
=> Action groups

src/Template/Element/action-header.ctp
After discussion with @lorenzo we've found that in the CRUD `add` action is specified as `entity` action.
This is the reason of the bug on the Add view (entity actions can't be rendered).
This PR provides a fix.
=> Fixed action bug on add view

src/Listener/ViewListener.php
This makes it so an action `tasksByUser` becomes "Tasks By User" in the UI, instead of "TasksByUser".
=> Fix action titles

config/asset_compress.ini, config/defaults.php
Using Livestamp.js, I ran into an issue with locales in moment.js:
Bumping the version means I can remove this temporary fix:
```php
// Force locale to English rather than the last locale loaded, Chinese.
// @todo Wait for https://github.com/moment/moment/issues/2367 to be closed.
// @todo Submit PR to bump moment.js version in CrudView
moment.locale('en'); // @todo Remove this line once above done.
```
=> Bump moment.js version

src/Listener/SearchListener.php
Not always a search field has to be "autocompletable" (for instance date/time filters). And in general it's nice to have possibility to customize "class" attribute.
=> Improved field "autocomplete" logic in SearchListener

src/Template/Layout/default.ctp, src/Template/Scaffold/index.ctp
The 'Delete' action is a post link but the block for it was only present on the index template.
Moving the block to the the same element means the button works on all pages it appears on.
https://github.com/FriendsOfCake/crud-view/blob/master/src/Template/Element/actions.ctp#L19
=> Move 'action_link_forms' block to layout

webroot/js/local.js
An empty value should not be converted to "01/01/1970...".
=> Added support for default empty datetime value

src/Listener/ViewListener.php
Allows you to `$action->config('scaffold.relations', false);` as opposed to blacklisting.
=> Allow disabling contain of all relations

src/View/Widget/DateTimeWidget.php
To be able to customize/disable the bootstrap datetime picker.
=> Allow overriding "role" attribute for DateTimeWidget

docs/customizing-templates.rst
Any values passed into the scaffold.fields config are passed to the FormHelper as input options allowing you to force an input type, set a default value, or perform any action the FormHelper provides. Also fixed 3 instances where $action->confg was used instead of $action->config.
=> Pass input values as options to Form Helper

src/Listener/ViewListener.php
Currently when viewing or editing an entity, the display field is used for the page title. If the entity has no display field, it defaults to `id`. This causes page titles like:
> Edit Post *#*4: 4
This is annoying and useless. I fixed this by not adding the display field value in case the display field is the same as the primary key.
=> Remove duplicate ID in page title

src/Listener/ViewListener.php
When setting actions using `$action->config('scaffold.actions', $actions);`, it ended up without any actions at all. When fetching actions from config, it checked against `null` and used to set it to `$this->_crud()->config('actions')` as a default. If the actions from config weren't `null`, it was set to `[]`.
Changed the code so it only reassigned `$actions` if it is `null`.
=> Fixed defining actions

config/asset_compress.ini, config/defaults.php, src/View/Widget/DateTimeWidget.php, webroot/js/local.js
This PR solves 2 issues I came across while implementing Crud-View in one of my projects. And I also bumped the version of the datepicker.
**First issue:**
locale_get_primary_language() was used to strip the locale, that didn't work with locales like `en_GB`.
Discussed in the following issue: https://github.com/FriendsOfCake/crud-view/issues/88.
**Second issue:**
The date picker somehow used the clients timezone, so if the time on server said 08:00 UTC, the date picker would use 10:00 +02:00. Originally I thought it was about Moment.js used in the bootstrap-datetimepicker, but it turned out to be code in this Crud-view.
To be clear, this issue only occurs when the app's timezone, defined in `bootstrap.php` does not match the timezone used in the web browser.
@lorenzo What's your thought …
=> Fix datepicker issues

src/Listener/ViewListener.php
Setting it to true allows specifying options for certain fields
without having to provide list of all fields in "scaffold.fields"
=> Add new config "scaffold.mergeFields".

webroot/css/local.css
Right now, icons are broken when using AssetCompress. This fixes it by using the CloudFlare's CDN (which is also configured in the AssetCompress build file) for the glyphicons font-face.
=> Use cloudflare's glyphicons

src/Listener/ViewListener.php
`$this->associations` is only populated in `beforeFind` or `beforePaginate`, this means that association fields are not loaded for `Add` actions. This change populates it in the `beforeFind` callback if it has not already been populated.
=> Read associations in beforeRender

config/defaults.php, src/View/CrudView.php
Don't like the implicit usage of AssetCompress helper. I use it for frontend but don't want to be bothered configuring crud view assets in asset_compress.ini for admin area.
=> Make usage of AssetCompress configurable.

src/Listener/ViewListener.php
Added the ability to alter the link text of controller actions using `label` like this:-
```php
public function index()
{
$action->config('scaffold.actions', ['edit', 'delete' => ['label' => __('Remove')]]);
return $this->Crud->execute();
}
```
The thinking behind this is that you don't always want the link text to read as the action name. For example:-
* You need to change the text without wanting to rename the action
* You need to translate the text using `__()`
I've used the config option `label` rather than `title` as you may still want to have a `title` attribute on the link and for accessibility this shouldn't be a duplicate of the link text.
=> Added ability to override controller action links’ text using `label`.

src/Template/Element/search.ctp
Button makes it clear what this form is performing, and a user can easily create a legend using the searchOptions, or replace this element with their own
=> Remove the legend on search

docs/quick-start.rst
Setting CrudView in intialize() prevents RequestHandler from switching view class based on request type.
=> Set CrudView in beforeRender()

src/Listener/ViewSearchListener.php
Field name is usually aliased and you end up with lookup action call like
`lookup.json?id=Posts.title&value=Posts.title&title=foo`
Due to this the "id" and "value" actually get ignored since LookupAction expects
the column names without prefix.
=> Use filter name itself as field name.

src/Listener/ViewListener.php
Controller and association names are already plural by convention.
Pluralizing them again creates problem for irregular plurals like "Salesmen".
Issue reported by "swimboy" on Slack.
=> Fix double pluralization.

src/Listener/ViewListener.php
When viewing a record that has associations belonging to a plugin the routes were broken, because the plugin parameter was hard coded to be null.
=> Plugins were hard coded as null

src/Template/Scaffold/view.ctp
Field title set through scaffold.fields/scaffold.field_settings was ignored in View action.
=> Display custom field title in View action

config/defaults.php, docs/_themes/cakephp/layout.html, docs/_themes/cakephp/static/css/style.css, docs/contents.rst, docs/site-title-options.rst, src/Listener/Traits/SiteTitleTrait.php, src/Listener/ViewListener.php, src/Template/Layout/default.ctp
This changes the `scaffold.brand` functionality to `scaffold.site_title`. You will now be allowed to customize the url as well as replace the content with an image.
=> Site title

docs/_themes/cakephp/static/css/app.css, docs/contents.rst, docs/customizing-templates.rst, docs/index-pages/components/blog.rst, docs/index-pages/components/custom.rst, docs/index-pages/components/table.rst, docs/index-pages/customizing-the-index-page.rst, src/Listener/Traits/IndexTypeTrait.php, src/Listener/Traits/SidebarNavigationTrait.php, src/Listener/ViewListener.php, src/Template/Element/index/blog.ctp, src/Template/Element/index/table.ctp, src/Template/Scaffold/index.ctp
This pull request introduces functionality that allows users to override the "table" contents of the index page. A reference `blog` index_type implementation is also included, and users are free to change the implementation to a custom element as they see fit.
=> Custom index pages

docs/customizing-templates.rst, src/Listener/Traits/SidebarNavigationTrait.php, src/Listener/ViewListener.php
We can now set `scaffold.sidebar_navigation` to false to disable the sidebar, and thus can remove that setting.
=> refactor: deprecate the scaffold.disable_sidebar config option

src/View/Widget/DateTimeWidget.php
DateFormatTrait::parseDate() by default uses format stored in $wordFormat for parsing date string.
Value of Time::$wordFormat differs from Date::$wordFormat hence using the former to parse date
strings results in incorrect date in the generated object.
=> Use Date::parseDate() to parse date only string.

composer.json, docs/contents.rst, docs/general-configuration/breadcrumbs.rst, src/Breadcrumb/ActiveBreadcrumb.php, src/Breadcrumb/Breadcrumb.php, src/Listener/ViewListener.php, src/Template/Element/breadcrumbs.ctp, src/Template/Layout/default.ctp, src/View/CrudView.php
- upgrade to at least bootstrap-ui 1.2
- pull blockquotes from `scaffold.breadcrumbs` configuration key
- introduce Breadcrumb and ActiveBreadcrumb classes
- add docs for all blockquote-related functionality
=> feat: add support for BootstrapUI Breadcrumbs

docs/contents.rst, docs/form-pages/customizing-the-form-page.rst, src/Listener/Traits/DeprecatedConfigurationKeyTrait.php, src/Listener/Traits/FormTypeTrait.php, src/Listener/ViewListener.php, src/Template/Element/form.ctp, src/Template/Element/form/buttons.ctp
- Adds much-needed documentation. I consider anything documented stable, and all else refactorable/removable.
- Replaced the `after_form/before_form` view blocks with `form.after_end/form.before_create` viewblocks. The old ones will render but will trigger a deprecation notice.
- Added `form.after_create/form.before_end` viewblocks.
- Namespaced the `submit_button_text` and `enable_dirty_check` options with the word `form`. Also changed the variable in use. The old variables will still take affect but will emit a deprecation notice.
- Created a new `form_submit_extra_buttons` configuration key. This allows total control of the form submit buttons. The configuration keys `scaffold.disable_extra_buttons` and `scaffold.extra_buttons_blacklist` will still take effect but will emit a …
=> refactor: Simplify forms

src/Listener/ViewListener.php
removed superflous ensureConfig() method from ViewListener class as it uses the CrudViewConfigTrait already
=> removed superflous ensureConfig() method from ViewListener class

docs/_partials/pages/index/filters.rst, docs/quick-start.rst, src/Listener/ViewSearchListener.php
What this PR does:
- Adds ability to specify the filter collection to use.
- ~~Adds `beforePaginate` callback which automatically applies `search` finder to the query.~~
Referring to changes #171:
> scaffold.index_filters = null|false: default, disable filters
I don't think not showing any filters is a good default. If you don't want any filter inputs to be generated one should just not load the listener or disable it.
> scaffold.index_filters = true: auto-import default search collection
> scaffold.index_filters = 'crud': auto-import a specific search collection
The `collection` option I added to the listener takes care of this.
> scaffold.index_filters = []: specific array of filter settings
The listener already has support for `fields` option to achieve the same. I have documented it.
=> SearchViewListener: filter collection

webroot/js/local.js
`$(document).on("ready", fn)` style usage has been removed in jquery 3.
See https://jquery.com/upgrade-guide/3.0/#deprecated-document-ready-handlers-other-than-jquery-function
=> Change "ready" handler usage.

src/Template/Element/action-groups.ctp
If you pass `null` as second param to HtmlHelper::tag() it will generate only opening tag.
=> Fix span tag generation.

src/View/CrudView.php
Using $this->template here is just plain wrong!
You want to use the $name argument here too of course!
Using $this->template breaks custom actions like so:
```
function beforeFilter($event) {
$this->Crud->mapAction('account', [
'className' => 'Crud.View',
'view' => 'view'
]);
}
function account() {
return $this->Crud->execute();
}
```
If there should be a valid case to use $this->template too, we need another try/catch block i suppose.
=> Template selection options not working

docs/_partials/fields/formatter-callable.rst
Maybe one should talk about the typehinting, as it's optional - for now it's in the second example while missing in the first. Hopefully that's obvious enough...
=> Add missing parameter

src/Listener/ViewListener.php
Prevents `array to string` notices.
=> Exclude scaffold settings from actions

docs/_partials/pages/index/buttons.rst
This makes the examples more clear.
=> docs: ensure we add scaffold.actions to action group examples

src/Listener/ViewListener.php
This allows users to avoid setting an empty config array.
=> fix: ensure that null configs are set to an empty array

composer.json, src/View/Widget/DateTimeWidget.php, tests/TestCase/View/Widget/DateTimeWidgetTest.php, tests/comparisons/View/Widget/DateTimeWidget/simple.html, tests/comparisons/View/Widget/DateTimeWidget/with-date-value.html, tests/comparisons/View/Widget/DateTimeWidget/with-string-value.html
If the input value failed validation, $val is going to be a string
Allow this:
Instead of this:
=> Do not try to format invalid string inputs

src/Template/Element/actions.ctp
- Don't mess with non-string URL array values.
This fixes `'plugin' => false` being converted to `'plugin' => ''`
- Don't search for :primaryKey: placeholder in URL array keys.
Can't think of any case where URL key would need primary key value.
=> Fix action links generation.

src/Listener/ViewSearchListener.php
FormHelper already sets label based on field name in similar manner. Setting label here
actually prevents the translation of labels which FormHelper does.
=> Don't set label for filter fields by default.

docs/_partials/pages/dashboard/elements.rst, docs/_partials/pages/dashboard/viewblocks.rst, docs/contents.rst, docs/dashboard-pages/customizing-the-dashboard-page.rst, src/Action/DashboardAction.php, src/Dashboard/Dashboard.php, src/Dashboard/Module/ActionLinkItem.php, src/Dashboard/Module/LinkItem.php, src/Listener/Traits/IndexTypeTrait.php, src/Listener/ViewListener.php, src/Template/Cell/DashboardTable/display.ctp, src/Template/Scaffold/dashboard.ctp, src/View/Cell/DashboardTableCell.php, src/View/CrudView.php, src/View/Helper/CrudViewHelper.php, tests/TestCase/Dashboard/DashboardTest.php, tests/TestCase/Dashboard/Module/ActionLinkItemTest.php, tests/TestCase/Dashboard/Module/LinkItemTest.php, webroot/css/local.css
Closes #185 
Example controller:
```
<?php
namespace App\Controller;
use CrudView\Dashboard\Dashboard;
use CrudView\Dashboard\Module\ActionLinkItem;
use CrudView\Dashboard\Module\LinkItem;
class DashboardController extends AppController
{
public function initialize()
{
parent::initialize();
$this->Crud->mapAction('dashboard', 'CrudView.Dashboard');
}
public function dashboard()
{
$dashboard = new Dashboard(__('Site Administration'));
$dashboard->addToColumn($this->cell('CrudView.DashboardTable', [
'links' => [
new ActionLinkItem('Posts', ['controller' => 'Posts'], [], [
new LinkItem('Add', ['controller' => 'Posts', 'action' => 'add']),
]),
]
]));
$dashboard->addToColumn($this->cell('CrudView.DashboardTable', [
'links' => [
new LinkItem('Facebook', 'https://www.facebook.com'),
new …
```
=> feat: Add DashboardAction

docs/_partials/pages/form/submit-buttons.rst, docs/_partials/pages/form/viewblocks.rst, src/Listener/Traits/FormTypeTrait.php, src/Template/Element/form/buttons.ctp
This will show a delete button by default on the left-hand side of non-AddAction pages.
Closes #186
=> feat: add support for extra left buttons

src/View/Helper/CrudViewHelper.php
\Cake\ORM\Entity requirement should be replaced with \Cake\Datasource\EntityInterface
This would make CrudViewHelper play nicely with other Entity classes like Muffin\Webservice\Model\Resource
=> Replace Entity with EntityInterface in CrudViewHelper

docs/general-configuration/sidebar-navigation.rst
By the way I'm not sure if the current behavior of `CrudViewConfigTrait` is intended. Once I add a `CrudView` key to my configuration (e.g. just `CrudView.tablesBlacklist`), all default options (including JS/CSS) go away:
https://github.com/FriendsOfCake/crud-view/blob/8903b77738723fdb6cb27c99d5c96a9592022a54/src/Traits/CrudViewConfigTrait.php#L18-L20
=> sidebar-navigation.rst: Fix tablesBlacklist key

src/Listener/ViewListener.php
The associations are inflected tabelized, not lowercased.
This is a prerequesite and doesn't need to be inflected here: $action->setConfig('scaffold.relations', ['users']); in a Controller throws an exception, 'Users' works.
=> Fix issue #280

src/View/Helper/CrudViewHelper.php
Changed return value of CrudViewHelper::schema() from TableSchemaInterface to more generic SchemaInterface for compatibility with non-table models
=> Compatibility with non-table models

src/Listener/ViewListener.php
When using the default configuration, related fields are displayed as ids. That is, they're not contained in the paginate query. The docs say the paginate query should automatically contain BelongsTo and HasOne associations but it doesn't.
With this change it works.
=> Fix using default relations
